package rosatech.integration.thaumcraft.recipe.additions

import gregtech.api.GTValues.*;
import rosatech.integration.thaumcraft.recipe.ESSENTIA_GENERATOR_RECIPES


class EssentiaGeneratorRecipes {

    companion object {

        fun init() {
            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("aer", 20)
                .circuitMeta(0)
                .duration(30)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("terra", 20)
                .duration(30)
                .circuitMeta(1)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("ignis", 20)
                .duration(30)
                .circuitMeta(2)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("aqua", 20)
                .duration(30)
                .circuitMeta(3)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("ordo", 20)
                .duration(30)
                .circuitMeta(4)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("perditio", 20)
                .duration(30)
                .circuitMeta(5)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("vacuos", 20)
                .duration(30)
                .circuitMeta(6)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("lux", 20)
                .duration(30)
                .circuitMeta(7)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("motus", 20)
                .duration(30)
                .circuitMeta(8)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("gelum", 20)
                .duration(30)
                .circuitMeta(9)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("vitreus", 20)
                .duration(30)
                .circuitMeta(10)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("metallum", 20)
                .duration(30)
                .circuitMeta(11)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("victus", 20)
                .duration(30)
                .circuitMeta(12)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("mortuus", 20)
                .duration(30)
                .circuitMeta(13)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("potentia", 20)
                .duration(60)
                .circuitMeta(14)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("praecantatio", 20)
                .duration(40)
                .circuitMeta(15)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("auram", 20)
                .duration(40)
                .circuitMeta(16)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("alkimia", 20)
                .duration(40)
                .circuitMeta(17)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("vitium", 20)
                .duration(40)
                .circuitMeta(18)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("tenebrae", 20)
                .duration(50)
                .circuitMeta(19)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("alienis", 20)
                .duration(55)
                .circuitMeta(20)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("volatus", 20)
                .duration(45)
                .circuitMeta(21)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("herba", 20)
                .duration(35)
                .circuitMeta(22)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("instrumentum", 25)
                .duration(50)
                .circuitMeta(23)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("fabrico", 20)
                .duration(55)
                .circuitMeta(24)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("machina", 30)
                .duration(70)
                .circuitMeta(25)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("vinculum", 25)
                .duration(60)
                .circuitMeta(26)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("spiritus", 20)
                .duration(40)
                .circuitMeta(27)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("cognitio", 25)
                .duration(60)
                .circuitMeta(28)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("sensus", 20)
                .duration(35)
                .circuitMeta(29)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("aversio", 25)
                .duration(40)
                .circuitMeta(30)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("praemunio", 20)
                .duration(40)
                .circuitMeta(31)
                .EUt(V[LV].toInt())
                .buildAndRegister()

            ESSENTIA_GENERATOR_RECIPES.recipeBuilder()
                .aspect("desiderium", 40)
                .aspect("praemunio", 20)
                .aspect("aversio", 25)
                .aspect("sensus", 20)
                .aspect("cognitio", 25)
                .aspect("spiritus", 20)
                .aspect("vinculum", 25)
                .aspect("machina", 30)
                .aspect("fabrico", 20)
                .aspect("instrumentum", 25)

                .aspect("aer", 100, true)
                .aspect("herba", 20, true)
                .aspect("volatus", 20, true)
                .aspect("alienis", 20, true)
                .aspect("tenebrae", 20, true)
                .aspect("vitium", 20, true)

                .duration(80)
                .circuitMeta(32)
                .EUt(V[LV].toInt())
                .buildAndRegister()
        }
    }
}